import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service | TalentIQ',
  description: 'The terms that govern your use of TalentIQ.',
}

const wrap: React.CSSProperties = { maxWidth: 760, margin: '0 auto', padding: '48px 20px 80px', color: 'rgba(245,242,235,.85)', fontFamily: 'Syne, sans-serif', lineHeight: 1.7 }
const h1: React.CSSProperties = { fontFamily: "'Cormorant Garamond', serif", fontSize: 34, fontWeight: 600, color: '#f5f2eb', marginBottom: 8 }
const h2: React.CSSProperties = { fontSize: 17, fontWeight: 700, color: '#d4af6d', marginTop: 32, marginBottom: 10 }
const p: React.CSSProperties = { fontSize: 14, marginBottom: 12, color: 'rgba(245,242,235,.7)' }
const li: React.CSSProperties = { fontSize: 14, marginBottom: 6, color: 'rgba(245,242,235,.7)' }

export default function TermsOfServicePage() {
  return (
    <div style={{ minHeight: '100vh', background: '#0a0a08' }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600&family=Syne:wght@400;500;600;700&display=swap');`}</style>
      <div style={wrap}>
        <Link href="/" style={{ fontSize: 12, color: '#d4af6d', textDecoration: 'none' }}>← TalentIQ</Link>
        <h1 style={h1}>Terms of Service</h1>
        <p style={{ fontSize: 12.5, color: 'rgba(245,242,235,.4)', marginBottom: 24 }}>Last updated: July 2026</p>

        <p style={p}>
          These Terms govern your use of TalentIQ. By creating an account or using our tools (including the
          public CV Builder), you agree to these Terms.
        </p>

        <h2 style={h2}>1. What TalentIQ Does</h2>
        <p style={p}>
          TalentIQ provides AI-assisted CV screening (for HR users evaluating candidates against a job
          description) and AI-assisted CV building (for candidates creating or improving a resume). Scores,
          verdicts, and suggestions are generated by an AI model and are provided as decision-support —
          not as a guarantee of a hiring outcome or job placement.
        </p>

        <h2 style={h2}>2. Accounts</h2>
        <ul style={{ paddingLeft: 18, marginBottom: 12 }}>
          <li style={li}>You must provide accurate information when signing up and verify your email address.</li>
          <li style={li}>You're responsible for keeping your password confidential and for all activity under your account.</li>
          <li style={li}>One account per person. Creating multiple accounts to bypass free-tier limits is not permitted.</li>
        </ul>

        <h2 style={h2}>3. Acceptable Use</h2>
        <p style={p}>You agree not to:</p>
        <ul style={{ paddingLeft: 18, marginBottom: 12 }}>
          <li style={li}>Upload content that is unlawful, someone else's private data without consent, or malicious files.</li>
          <li style={li}>Use the CV Builder to fabricate false work experience, credentials, or qualifications — the tool is designed to present your real experience clearly, not to invent one.</li>
          <li style={li}>Attempt to bypass rate limits, free-tier caps, or authentication via automation, scripting, or abuse of the anonymous-access flow.</li>
          <li style={li}>Reverse-engineer, scrape, or resell the service without our permission.</li>
        </ul>

        <h2 style={h2}>4. Free Tier & Paid Plans</h2>
        <p style={p}>
          Candidate accounts include a limited number of free CV scans and CV builds. HR accounts operate on
          a paid subscription for full access. We may change free-tier limits or pricing going forward;
          material changes will be communicated in advance where practical.
        </p>

        <h2 style={h2}>5. AI-Generated Content — Accuracy Disclaimer</h2>
        <p style={p}>
          Screening scores, verdicts, and CV rewrites are generated by a large language model and may contain
          errors or miss context a human reviewer would catch. HR users should use TalentIQ's output as one
          input among several in a hiring decision, not as the sole basis for accepting or rejecting a
          candidate. Candidates should review any AI-generated CV content for accuracy before submitting it
          to employers.
        </p>

        <h2 style={h2}>6. Your Content</h2>
        <p style={p}>
          You retain ownership of the CVs, job descriptions, and other content you upload. By uploading
          content, you grant us a limited license to process it (including sending it to our AI provider)
          solely to provide the service to you.
        </p>

        <h2 style={h2}>7. Termination</h2>
        <p style={p}>
          You may delete your account at any time from Settings. We may suspend or terminate accounts that
          violate these Terms, including abuse of free-tier limits or unlawful use of the platform.
        </p>

        <h2 style={h2}>8. Limitation of Liability</h2>
        <p style={p}>
          TalentIQ is provided "as is." To the extent permitted by law, we are not liable for hiring
          decisions, job outcomes, or damages arising from reliance on AI-generated scores or content.
        </p>

        <h2 style={h2}>9. Changes to These Terms</h2>
        <p style={p}>We may update these Terms as the product evolves. Continued use after changes take effect constitutes acceptance.</p>

        <h2 style={h2}>10. Contact</h2>
        <p style={p}>Questions about these Terms? Reach out at <strong>[your contact email here]</strong>.</p>
      </div>
    </div>
  )
}